version: "3.9"

services:
  postgres:
    container_name: db_iot_sensor
    image: postgres:latest
    environment:
      POSTGRES_USER: HiepData
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db_iot_sensor
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata_iot:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    restart: unless-stopped

volumes:
  pgdata_iot:
